# SIMD intrinsics for BG/P
if ENABLE_IBM_INTRINSICS
include passes/pass2/ppc450/Makefile.insert
endif

#SIMD intrinsics for Intel/AMD
if ENABLE_SSE2_INTRINSICS
include passes/pass2/sse2/Makefile.insert
endif

# fallback mode TODO: introduce DISABLED SIMD to provide disjoint sets of if tests
if !ENABLE_IBM_INTRINSICS
if !ENABLE_SSE2_INTRINSICS
include passes/pass2/generic/Makefile.insert
endif
endif
