#! /bin/sh
# Setup autotools infrastructure 
# This file is not distributed and is only needed by developers.

for dir in build-aux m4; do
  if test ! -d "$dir" && test ! -f "$dir"; then
    mkdir "$dir"
  fi
done

autoreconf --verbose --install --force $@

# Fixup a nasty bug present even in fairly new depcomp scripts,
# that may show up on BlueGene.
if grep 'makedepend.*VPATH' build-aux/depcomp >/dev/null 2>&1
then :
else
  patch -b -p0 2>/dev/null <<\EOF
--- build-aux/depcomp
+++ build-aux/depcomp
@@ -425,7 +425,9 @@
   touch "$tmpdepfile"
   ${MAKEDEPEND-makedepend} -o"$obj_suffix" -f"$tmpdepfile" "$@"
   rm -f "$depfile"
-  cat < "$tmpdepfile" > "$depfile"
+  # makedepend may prepend the VPATH from the source file name to the object.
+  sed_object_re=`echo $object | sed 's/[].[^$\\*|]/\\\\&/g'`
+  sed "s|^.*\($sed_object_re *:\)|\1|" "$tmpdepfile" > "$depfile"
   sed '1,2d' "$tmpdepfile" | tr ' ' '
 ' | \
 ## Some versions of the HPUX 10.20 sed can't process this invocation
EOF
fi

# Add dependency tracking support for IBM C/C++ xlc/xlC Compilers
if grep 'xlc' build-aux/depcomp >/dev/null 2>&1
then :
else
  patch -b -p0 2>/dev/null <<\EOF
--- build-aux/depcomp.orig
+++ build-aux/depcomp
@@ -102,6 +102,12 @@
    depmode=msvc7
 fi
 
+if test "$depmode" = xlc; then
+   # IBM C/C++ Compilers xlc/xlC can output gcc-like dependency informations.
+   gccflag=-qmakedep=gcc,-MF
+   depmode=gcc
+fi
+
 case "$depmode" in
 gcc3)
 ## gcc 3 implements dependency tracking that does exactly what
@@ -226,6 +232,13 @@
   rm -f "$tmpdepfile"
   ;;
 
+xlc)
+  # This case exists only to let depend.m4 do its work.  It works by
+  # looking at the text of this script.  This case will never be run,
+  # since it is checked for above.
+  exit 1
+  ;;
+
 aix)
   # The C for AIX Compiler uses -M and outputs the dependencies
   # in a .u file.  In older versions, this file always lives in the
EOF
fi

# Fix broken space handling of libtool
if grep 'test x-L = "x$p"' configure >/dev/null 2>&1
then :
else
  if grep 'test x-L = "$p"' configure >/dev/null 2>&1
  then
    patch -b -p0 2>/dev/null <<\EOF
--- configure.orig	2016-03-03 10:25:22.360544857 +0100
+++ configure	2016-03-03 10:27:41.848727662 +0100
@@ -17785,10 +17785,11 @@
     case $prev$p in
 
     -L* | -R* | -l*)
-       # Some compilers place space between "-{L,R}" and the path.
+       # Some compilers place space between "-{L,R,l}" and the path.
        # Remove the space.
-       if test x-L = "$p" ||
-          test x-R = "$p"; then
+       if test x-L = "x$p" ||
+          test x-R = "x$p" ||
+          test x-l = "x$p" ; then
 	 prev=$p
 	 continue
        fi
@@ -19766,10 +19767,11 @@
     case $prev$p in
 
     -L* | -R* | -l*)
-       # Some compilers place space between "-{L,R}" and the path.
+       # Some compilers place space between "-{L,R,l}" and the path.
        # Remove the space.
-       if test x-L = "$p" ||
-          test x-R = "$p"; then
+       if test x-L = "x$p" ||
+          test x-R = "x$p" ||
+          test x-l = "x$p"; then
 	 prev=$p
 	 continue
        fi
EOF
  fi
fi

if grep 'test $p = "-l"' configure >/dev/null 2>&1
then :
else
  if grep 'test $p = "-L"' configure >/dev/null 2>&1
  then
    patch -b -p0 2>/dev/null <<\EOF
--- configure.orig	2016-12-11 00:06:46.000000000 +0100
+++ configure	2016-12-11 00:09:58.376546677 +0100
@@ -17287,10 +17287,11 @@
     case ${prev}${p} in
 
     -L* | -R* | -l*)
-       # Some compilers place space between "-{L,R}" and the path.
+       # Some compilers place space between "-{L,R,l}" and the path.
        # Remove the space.
        if test $p = "-L" ||
-          test $p = "-R"; then
+          test $p = "-R" ||
+          test $p = "-l"; then
 	 prev=$p
 	 continue
        fi
@@ -19205,10 +19206,11 @@
     case ${prev}${p} in
 
     -L* | -R* | -l*)
-       # Some compilers place space between "-{L,R}" and the path.
+       # Some compilers place space between "-{L,R,l}" and the path.
        # Remove the space.
        if test $p = "-L" ||
-          test $p = "-R"; then
+          test $p = "-R" ||
+          test $p = "-l"; then
 	 prev=$p
 	 continue
        fi
EOF
  fi
fi
