# single precision intrinsics
# fallback mode: TODO: provide SP intrinsics for PPC450 
#if FCS_FLOAT_IS_FLOAT
#simd_sources += \
#        passes/pass2/generic/pass2trfrqdcach.f90
#endif

# double precision intrinsics 
#if FCS_FLOAT_IS_DOUBLE
simd_sources += \
        passes/pass2/ppc450/64bit/pass2trfrqdcach.f90
#endif

pass2trfrqdcach.$(OBJEXT): ../../../../fconfig.h
